version: '3'
services:
  api:
    container_name: api
    build: .
    command: bash -c "npm install && npm run dev"
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
  database:
    image: mysql:5.7.32
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
